# Generated by Django 5.1.7 on 2025-06-15 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('document', models.FileField(upload_to='pdfs/')),
                ('comment', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
